version: '3.8'
services:
  api:
    image: student-gql
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/student_db
      NODE_ENV: development
      PORT: 3000
    ports:
      - '8080:3000'

  postgres:
    image: postgres
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_db
